from datetime import datetime, timezone
from typing import Literal, Optional
from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    LargeBinary,
    String,
    Text,
    UniqueConstraint,
)
from pydantic import BaseModel
from database import Base


def utcnow():
    return datetime.now(timezone.utc)


PostCategory = Literal["flood", "landslide", "storm", "rescue", "other"]
WaterLevel = Literal["none", "ankle", "knee", "waist", "chest", "over_head"]


class Post(Base):
    """A real-time report shared by a community member."""

    __tablename__ = "Posts"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    # Random id generated by the app on first launch; never returned to other users.
    device_id = Column(String(64), nullable=False, index=True)
    author_name = Column(String(40), nullable=False)
    category = Column(String(20), nullable=False, default="flood")
    water_level = Column(String(20), nullable=True)
    description = Column(Text, nullable=False)
    latitude = Column(Float, nullable=False, index=True)
    longitude = Column(Float, nullable=False, index=True)
    address = Column(String(255), nullable=True)
    # File name of the photo in PostImages, e.g. "3f2a...c1.jpg"
    image_path = Column(String(255), nullable=True)
    created_at = Column(DateTime(timezone=True), nullable=False, default=utcnow, index=True)
    confirm_count = Column(Integer, nullable=False, default=0)
    report_count = Column(Integer, nullable=False, default=0)
    hidden = Column(Boolean, nullable=False, default=False)


class PostImage(Base):
    """Photo of a post, stored in the database so it survives redeploys on hosts without a
    persistent disk (Render/Railway free plans)."""

    __tablename__ = "PostImages"

    name = Column(String(40), primary_key=True)
    data = Column(LargeBinary, nullable=False)
    created_at = Column(DateTime(timezone=True), nullable=False, default=utcnow)


class PostVote(Base):
    """A 'confirm' (still happening) or 'report' (abuse) vote on a post, one per device."""

    __tablename__ = "PostVotes"
    __table_args__ = (UniqueConstraint("post_id", "device_id", "kind"),)

    id = Column(Integer, primary_key=True, autoincrement=True)
    post_id = Column(Integer, ForeignKey("Posts.id", ondelete="CASCADE"), nullable=False, index=True)
    device_id = Column(String(64), nullable=False)
    kind = Column(String(10), nullable=False)
    reason = Column(String(200), nullable=True)
    created_at = Column(DateTime(timezone=True), nullable=False, default=utcnow)


class PostResponse(BaseModel):
    id: int
    author_name: str
    # Stable pseudonymous id so the app can let users block an author.
    author_id: str
    category: str
    water_level: Optional[str]
    description: str
    latitude: float
    longitude: float
    address: Optional[str]
    image_url: Optional[str]
    created_at: datetime
    confirm_count: int
    distance_km: Optional[float] = None
    is_mine: bool = False
    confirmed_by_me: bool = False


class PostListResponse(BaseModel):
    posts: list[PostResponse]


class ConfirmResponse(BaseModel):
    confirm_count: int
    confirmed_by_me: bool


class ReportRequest(BaseModel):
    reason: str = ""
